name: Github4s
baseurl: /github4s
description: Github API wrapper written in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.18.9-SNAPSHOT
org: 47 Degrees
markdown: kramdown
