name: Github4s
description: "A GitHub API wrapper written in Scala"
github_owner: 47deg
baseurl: /github4s
style: github4s
highlight_theme: tomorrow
docs: true

markdown: redcarpet
collections:
  tut:
    output: true
